const Types = {
  AUTH_LOADING: 'AUTH_LOADING',
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  SIGN_ERROR: 'SIGN_ERROR',
  SIGN_OUT: 'SIGN_OUT',

  ACCOUNT_LOADING: 'ACCOUNT_LOADING',
  ACCOUNT_BALANCE: 'ACCOUNT_BALANCE',
  ACCOUNT_ALL: 'ACCOUNT_ALL',
  ACCOUNT_EDIT: 'ACCOUNT_EDIT',

  TRANSACTION_LOADING: 'TRANSACTION_LOADING',
  TRANSACTION_USER_ID: 'TRANSACTION_USER_ID',
  TRANSACTION_BANK_USER_DEPOSIT: 'TRANSACTION_BANK_USER_DEPOSIT',

  FINANCIAL_LOADING: 'FINANCIAL_LOADING',
  FINANCIAL_ALL: 'FINANCIAL_ALL'
};
export default Types;
